#[theme]
#primaryColor = "#0e4e40"
#backgroundColor = "#f5f7f3"
#secondaryBackgroundColor = "#c9eab8"
#textColor = "#262730"
#font = "sans serif"

[theme]
primaryColor = "#757575"  # Unchanged for now
backgroundColor = "#000000"  # Black background
secondaryBackgroundColor = "#333333"  # Dark gray secondary background
textColor = "#FFFFFF"  # White text
font = "monospace"

[server]
port = 8502
enableStaticServing = true

[browser]
gatherUsageStats = false
